services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - app-network
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: 'Dockerfile.local'
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8000:8000"
    networks:
      - app-network
    command: >
      sh -c "
      while ! nc -z db 5432 || ! nc -z redis 6379; do sleep 1; done;
      python src/manage.py makemigrations &&
      python src/manage.py migrate &&
      python src/manage.py collectstatic --noinput &&
      python src/manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    networks:
      - app-network



volumes:
  db-data:
  static-data:
  media-data:

networks:
  app-network:
    driver: bridge